### ISSUE TITLE
JwtParser 삭제

### ISSUE THREAD

**Issue by leeseojune53** [team-xquare/v1-service-application#81]
### Describe

<img width="803" alt="스크린샷 2022-06-11 오전 1 34 34" src="https://user-images.githubusercontent.com/61784568/173111501-409eed2a-eac6-42c9-b23c-8019b8d4ebbc.png">

요런식으로 수정해야할듯 

그리고 secret key must at least 256bit라는 오류 떠서 secret key가 좀 길어야하거나 인코딩해야할듯?

### Work

- [ ] JwtParser.java

**Comment by parksangwoo1617** [comment]
jwt parser 어차피 이제 안 쓰자너

**Comment by leeseojune53** [comment]
그러면 토큰인증부분을 빼야할거같은데 프론트 연동을 못해

**Comment by parksangwoo1617** [comment]
그럼 지금 토큰 인증 부분 빼고 그냥 다 permitAll 해놓자

**Comment by parksangwoo1617** [comment]
어차피 게이트웨이 나와야 제대로 된 테스트 가능할 거 같은데 지금은 그냥 연동되는지만 확인해도 괜찮을듯

**Comment by parksangwoo1617** [comment]
내가 해??

**Comment by leeseojune53** [comment]
예압! 나 집보러왔어

**Comment by parksangwoo1617** [comment]
오키 잘 보고와잉
